### ISSUE TITLE
Parse Flatsat API

### ISSUE THREAD

**Issue by rima1881** [rima1881/Flat-Earthers-Backend#1]

**Comment by bryjen** [comment]
## Dataset Observation
We can limit the datasets to query for based on the dataset category name. In general, `Landsat Collection 2 Level-x` (where x is either 1, 2, 3) contains all data collected by landsat satellites 8 and 9. These datasets are further categorized by what type of data they collect (categorized by wavelength spectrums). 

From my understanding, the dataset containing colored RGB images that can be displayed to the user is `landsat_ot_c2_l2`. There may be other datasets that provide similar images. This is the only dataset I'm aware of as of right now. 
[updated-datasets.json](https://github.com/user-attachments/files/17003437/updated-datasets.json)

**Comment by rima1881** [comment]
yeah i saw that in their api thingy

**Comment by bryjen** [comment]
# Algorithm to Predict Next Acquisition Date

## Prerequisite Knowledge
- [Scenes](https://landsatlook.usgs.gov/gen-browse?size=rrb&type=refl&product_id=LC09_L1TP_014028_20240911_20240911_02_T1) are labelled by **path** and **row**. Scenes with the same path & row over different times photograph the same area.
- The USGS api endpoint ``scene-search`` returns a list from a dataset given some filters (time, location, and metadata filters).
- The USGS api endpoint ``sence-metadata`` returns a detailed list of metadata given a specific scene.
- A landsat satellite takes a picture of a specific scene once every 16 days.

## Overview
![image](https://github.com/user-attachments/assets/4da2deae-09ea-4ec3-b5f0-84c1b535514e)
The process consists of 3 main steps:
1. Given a path and row (and current time), get all scenes with similar paths and rows.
2. For each scenes, get all the metadata associated with it.
3. From the information in the metadata, calculate the next predicted acquisition date.

### 1. Getting the scenes
- The ``scene-search`` endpoint has parameters for a ``temporalFilter`` (for dates), ``spatialFilter`` (for coordinates), and ``metadataFilter``.
  We set a temporal interval between today and some time ago (at least a month or two).
  We set a spatial filter for the area we want to query (using latitude and longitude).
- The path and row of a scene is defined in its metadata. So set a metadata filter for the given path and row.
- From the returned data, we only extract the ``entity-id``

### 2. Getting the extra metadata
- Not all of the required metadata is provided from the query to ``scene-search``
- Therefore, we have to call a separate endpoint ``scene-metadata`` given our entity id to get all the metadata we need.
- This metadata consists of the dates of the image, as well as the landsat satellite that took it.
- From the response, we only take those pieces of data.

### 3. Calculating the next acquisition date
Given the times of each scene, the straightforward approach would be average out the timespans between two consecutive scenes.  However, even though both landsat 8 and 9 satellites operate over the same 16 day interval, both start at different offsets. So we have to identify which satellite took the last photo (lets take 8 for example), then we have to perform some calculations on the other satellite (9, continuing from the previous example).

The general algorithm then is:
1. Get a list of acquisition times
2. Calculate the mean timespan between each entry
3. Add the mean timespan to the latest (most recent time) in the list.

**Comment by bryjen** [comment]
## Observation on date metadata
Date information is included in four metadata fields, ``DateProductGeneratedL1``, ``DateProductGeneratedL2``, ``StartTime``, and ``StopTime``.
I assume that 'DateProductGenerated' is when the data is made available to the api, and that l1 and l2 describe what level they were collected in (still unsure what that exactly means as well).

An interesting observation is that scene data collected by landsat 9 has the same day for 'DateProductGenerated', 'StartTime', and 'EndDate'.
However, for landsat 8, the 'DateProductGenerated' value is several days ahead compared to the date listed in 'StartTime' and 'EndDate'.
This suggests that landsat 8 takes some time to upload the data to the database after it has 'collected' the data. 
This is assuming that 'DateProductGenerated' represents when the scene data is made available in the database or through the api.

**Comment by bryjen** [comment]
As of right now, we've completely figured out the serialization/deserialization of requests and responses from the usgs m2m endpoint `scene-search` (and `login-token`). If we need to query other endpoints, it should follow roughly the same serialization/deserialization logic as these two endpoints. 

Details of additional endpoints should be written here.

**Comment by bryjen** [comment]
New API endpoints were now made compatible in the backend:
- `scene-list-add` Takes in a name and a list of scene `entityId`s.
- `scene-list-get` Returns a list of `entityId`s belonging to a particular list, if it exists.
- `scene-metadata-list` Returns a list of metadata for each scene in a list, if it exists.
